from flask import Flask, render_template, request, Response
import random
import requests
import os
import datetime
import json
from resources.headers import headers
import resources.socialLinks

app = Flask(__name__)

OUTPUT_FOLDER = "output"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)


def scan(username):

    if not username:
        yield "data: {}\n\n"
        return

    file_path = f"{OUTPUT_FOLDER}/{username}.txt"
    x = datetime.datetime.now()

    with open(file_path, "a", encoding="utf-8") as file:
        file.write(
            f"\n\n# Generated By Kexer\n"
            f"Result Generated at {x.strftime('%X %x')}\n\n"
        )

    links = resources.socialLinks.links
    total = len(links)
    scanned = 0

    for site, base_url in links.items():
        scanned += 1

        try:
            url = base_url.format(username)

            response = requests.get(
                url,
                headers={"User-Agent": random.choice(headers)},
                timeout=6
            )

            if response.status_code == 200:
                result = {
                    "site": site,
                    "url": url,
                    "status": "found",
                    "scanned": scanned,
                    "total": total
                }

                with open(file_path, "a", encoding="utf-8") as file:
                    file.write(url + "\n")

            else:
                result = {
                    "site": site,
                    "status": "not_found",
                    "scanned": scanned,
                    "total": total
                }

        except requests.exceptions.RequestException:
            result = {
                "site": site,
                "status": "error",
                "scanned": scanned,
                "total": total
            }

        yield f"data: {json.dumps(result)}\n\n"


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/results")
def results():
    username = request.args.get("username")
    return render_template("results.html", username=username)


@app.route("/scan")
def run_scan():
    username = request.args.get("username")

    headers_stream = {
        "Cache-Control": "no-cache",
        "Connection": "keep-alive"
    }

    return Response(
        scan(username),
        headers=headers_stream,
        mimetype="text/event-stream"
    )


if __name__ == "__main__":
    app.run(debug=True, threaded=True)
