from flask import Flask, render_template, request, Response
import random
import requests
import os
import datetime
import json
from resources.headers import headers
import resources.socialLinks

app = Flask(__name__)

OUTPUT_FOLDER = "output"

if not os.path.exists(OUTPUT_FOLDER):
    os.mkdir(OUTPUT_FOLDER)


def scan(username):
    file_path = f"{OUTPUT_FOLDER}/{username}.txt"
    x = datetime.datetime.now()

    with open(file_path, "a") as file:
        file.write(
            f"\n\n# Generated By Kexer\n"
            f"Result Generated at {x.strftime('%X %x')}\n\n"
        )

    for site in resources.socialLinks.links:
        url = resources.socialLinks.links[site].format(username)

        try:
            response = requests.get(
                url,
                headers={"User-Agent": random.choice(headers)},
                timeout=5
            )

            if response.status_code == 200:
                result = {"site": site, "url": url, "status": "found"}

                with open(file_path, "a") as file:
                    file.write(url + "\n")

            else:
                result = {"site": site, "url": url, "status": "not_found"}

        except:
            result = {"site": site, "url": url, "status": "error"}

        yield f"data: {json.dumps(result)}\n\n"


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/scan")
def run_scan():
    username = request.args.get("username")
    return Response(scan(username), mimetype="text/event-stream")


app.run(debug=True)
